"""performance test user id fk

Revision ID: 52efc97a240f
Revises: 6e8c538b88d0
Create Date: 2025-01-30 13:45:51.817677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52efc97a240f'
down_revision: Union[str, None] = '6e8c538b88d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_test', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'performance_test', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'performance_test', type_='foreignkey')
    op.drop_column('performance_test', 'user_id')
    # ### end Alembic commands ###
