"""analytics unique constraint

Revision ID: 65da41dc5c8e
Revises: 6826a46bf43a
Create Date: 2025-03-05 16:58:27.778828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65da41dc5c8e'
down_revision: Union[str, None] = '6826a46bf43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_test_date_performance_test', 'analytics', ['test_date', 'performance_test_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_test_date_performance_test', 'analytics', type_='unique')
    # ### end Alembic commands ###
