"""analytics model

Revision ID: 2ff1097e19f3
Revises: 62aad929d98a
Create Date: 2025-02-28 18:02:31.523413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff1097e19f3'
down_revision: Union[str, None] = '62aad929d98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('performance_test_id', sa.Integer(), nullable=False),
    sa.Column('performance_test_result', sa.Float(precision=2), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['performance_test_id'], ['performance_test.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics')
    # ### end Alembic commands ###
