"""initial revision

Revision ID: 16c3ffb388aa
Revises: 
Create Date: 2025-01-02 18:22:10.614156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c3ffb388aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('hashed_password', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('training_plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=30), nullable=False),
    sa.Column('performance_value', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('training_plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_exercise',
    sa.Column('training_plan_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plan.id'], ),
    sa.PrimaryKeyConstraint('training_plan_id', 'exercise_id')
    )
    op.create_table('weekly_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', name='weekday'), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_schedule')
    op.drop_table('training_exercise')
    op.drop_table('performance_test')
    op.drop_table('exercise')
    op.drop_table('training_plan')
    op.drop_table('users')
    # ### end Alembic commands ###
