"""user on schedule

Revision ID: 6e8c538b88d0
Revises: bc571e940032
Create Date: 2025-01-15 17:18:21.110189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8c538b88d0'
down_revision: Union[str, None] = 'bc571e940032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_schedule', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'weekly_schedule', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weekly_schedule', type_='foreignkey')
    op.drop_column('weekly_schedule', 'user_id')
    # ### end Alembic commands ###
