"""secondary tp perftest table

Revision ID: 9b560d371645
Revises: 65da41dc5c8e
Create Date: 2025-03-06 17:31:26.301624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9b560d371645'
down_revision: Union[str, None] = '65da41dc5c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_performance_test',
    sa.Column('training_plan_id', sa.Integer(), nullable=False),
    sa.Column('performance_test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['performance_test_id'], ['performance_test.id'], ),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plan.id'], ),
    sa.PrimaryKeyConstraint('training_plan_id', 'performance_test_id')
    )
    op.drop_constraint('performance_test_ibfk_1', 'performance_test', type_='foreignkey')
    op.drop_column('performance_test', 'training_plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_test', sa.Column('training_plan_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('performance_test_ibfk_1', 'performance_test', 'training_plan', ['training_plan_id'], ['id'])
    op.drop_table('training_performance_test')
    # ### end Alembic commands ###
