"""increase hashed_password len

Revision ID: c609d3eafb00
Revises: de05259a422c
Create Date: 2025-01-08 17:18:52.376316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c609d3eafb00'
down_revision: Union[str, None] = 'de05259a422c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###
