"""add sets column

Revision ID: 3f6904f16631
Revises: 9b560d371645
Create Date: 2025-03-07 19:20:36.893860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6904f16631'
down_revision: Union[str, None] = '9b560d371645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('sets', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'sets')
    # ### end Alembic commands ###
