"""add schedule to exercise relationship

Revision ID: bc571e940032
Revises: 46fe2aa000e2
Create Date: 2025-01-13 15:51:03.860483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bc571e940032'
down_revision: Union[str, None] = '46fe2aa000e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_schedule_exercise',
    sa.Column('weekly_schedule_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['weekly_schedule_id'], ['weekly_schedule.id'], )
    )
    op.drop_constraint('exercise_ibfk_1', 'exercise', type_='foreignkey')
    op.drop_column('exercise', 'training_plan_id')
    op.drop_constraint('weekly_schedule_ibfk_1', 'weekly_schedule', type_='foreignkey')
    op.drop_column('weekly_schedule', 'exercise_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_schedule', sa.Column('exercise_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('weekly_schedule_ibfk_1', 'weekly_schedule', 'exercise', ['exercise_id'], ['id'])
    op.add_column('exercise', sa.Column('training_plan_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('exercise_ibfk_1', 'exercise', 'training_plan', ['training_plan_id'], ['id'])
    op.drop_table('weekly_schedule_exercise')
    # ### end Alembic commands ###
