"""add user fk to exercise

Revision ID: 46fe2aa000e2
Revises: c609d3eafb00
Create Date: 2025-01-09 10:44:45.568774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fe2aa000e2'
down_revision: Union[str, None] = 'c609d3eafb00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'exercise', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.drop_column('exercise', 'user_id')
    # ### end Alembic commands ###
