"""many to many performance schedule

Revision ID: 31af7810c821
Revises: 52efc97a240f
Create Date: 2025-02-03 15:37:07.636387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31af7810c821'
down_revision: Union[str, None] = '52efc97a240f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_schedule_performance_test',
    sa.Column('weekly_schedule_id', sa.Integer(), nullable=True),
    sa.Column('performance_test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['performance_test_id'], ['performance_test.id'], ),
    sa.ForeignKeyConstraint(['weekly_schedule_id'], ['weekly_schedule.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_schedule_performance_test')
    # ### end Alembic commands ###
