"""cascade delete analytics with perf test

Revision ID: 6826a46bf43a
Revises: 62aad929d98a
Create Date: 2025-03-05 13:59:28.237869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6826a46bf43a'
down_revision: Union[str, None] = '62aad929d98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('analytics_ibfk_1', 'analytics', type_='foreignkey')
    op.create_foreign_key(None, 'analytics', 'performance_test', ['performance_test_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analytics', type_='foreignkey')
    op.create_foreign_key('analytics_ibfk_1', 'analytics', 'performance_test', ['performance_test_id'], ['id'])
    # ### end Alembic commands ###
