"""First revision

Revision ID: 9bc72df6d092
Revises: 
Create Date: 2025-01-01 21:43:34.871668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9bc72df6d092'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('exercise_name', sa.String(length=30), nullable=False))
    op.drop_column('exercise', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('name', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('exercise', 'exercise_name')
    # ### end Alembic commands ###
