"""add link to exercise

Revision ID: 0bde305762b9
Revises: 3f6904f16631
Create Date: 2025-04-09 09:05:57.475344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0bde305762b9'
down_revision: Union[str, None] = '3f6904f16631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('link', sa.String(length=200), nullable=True))
    op.alter_column('exercise', 'exercise_name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=60),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise', 'exercise_name',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('exercise', 'link')
    # ### end Alembic commands ###
